{% set name = "pyEDFlib" %}
{% set version = "0.1.36" %}
{% set sha256 = "3ae985444e673285e0eae552696205daf36164eeea71010ae35be3e2a4bc7525" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyedflib

about:
  home: https://github.com/holgern/pyedflib
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/holgern/pyedflib
  doc_url: http://pyedflib.readthedocs.io/
  summary: Library to read/write EDF+/BDF+ files based on EDFlib.

extra:
  recipe-maintainers:
    - skjerns
    - holgern
