{% set name = "pyEDFlib" %}
{% set version = "0.1.25" %}
{% set sha256 = "5b5828cf20e4447721dc5d441f27d4af2939f57cf002734b61a05fc1e6cc7cd1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
  imports:
    - pyedflib
  commands:

about:
  home: https://github.com/holgern/pyedflib
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/holgern/pyedflib
  doc_url: http://pyedflib.readthedocs.io/
  summary: Library to read/write EDF+/BDF+ files based on EDFlib.

extra:
  recipe-maintainers:
    - holgern
