appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: apUm3HF9QQHC3zAaaDSlBRH5Bw0ZENz0C0G6WXyHuL1yGOqulLB4+CmfXcaX+QTFCYEDNe8yfbZMIlQTB17wu7XEFvkEJnkerpdrejXwtiUFMGSlGSxBSGeef70AsDa4EMdDmofzQSCJ927aB87zoeHEELXP69MnNvLTi49Zq+8qF3l1kCETlUG1/tOcvFOQ4x8IY52J4kV8gO6Xfjv9toZ5ptBRDL7lq58MXkkB0ihkdP13Ac9hT473xkbfKwj8WYedPJHrvmAfGRPHL7IPzIu9kLy7x1RhAVQAsK53zfNncL+CugpCpUTpDW1XHzFMleaoFRPryluHj30qUcTOKti7tEzy7SFpHq0DP/CyfrqAe1WlsBDD560jTJdL8QF7IRVAxKNdZN9EqP2cccmfjXjVoZ+jQTiN6jezS6Bb3u2uTzzAUoAIVJ3o8OSOLS1oA4nfaLhScdzlf2fpAwKWpJXSqe4EjBEvuYuuX2lib9X/KA2/2/Jynur2ylDaIeXSuc5Zx6b4o26rUs2CeeYqSRo+GVFNRUdjQjreBHFttq2GdJ0IlNwcz+7F/MxCW1HAh3O+L4BE4tPEfSXS/TB4jdvwoL3ziUraLDD/oxit/I78E7J+rhZR5RNcGxu/GbX/vBugTC8JaYiE64nVtoUGo93lLO7Hi2ZfnkPRgOYzCzg=}
